// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockstorage

import (
	context "context"
	model "gkeeper/internal/model"

	mock "github.com/stretchr/testify/mock"
)

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, userID, title, secretType, encryptedData, metadata, filePath
func (_m *MockStorage) CreateSecret(ctx context.Context, userID string, title string, secretType string, encryptedData string, metadata string, filePath string) (*model.Secret, error) {
	ret := _m.Called(ctx, userID, title, secretType, encryptedData, metadata, filePath)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (*model.Secret, error)); ok {
		return rf(ctx, userID, title, secretType, encryptedData, metadata, filePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) *model.Secret); ok {
		r0 = rf(ctx, userID, title, secretType, encryptedData, metadata, filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, title, secretType, encryptedData, metadata, filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockStorage_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - title string
//   - secretType string
//   - encryptedData string
//   - metadata string
//   - filePath string
func (_e *MockStorage_Expecter) CreateSecret(ctx interface{}, userID interface{}, title interface{}, secretType interface{}, encryptedData interface{}, metadata interface{}, filePath interface{}) *MockStorage_CreateSecret_Call {
	return &MockStorage_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, userID, title, secretType, encryptedData, metadata, filePath)}
}

func (_c *MockStorage_CreateSecret_Call) Run(run func(ctx context.Context, userID string, title string, secretType string, encryptedData string, metadata string, filePath string)) *MockStorage_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockStorage_CreateSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockStorage_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateSecret_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string) (*model.Secret, error)) *MockStorage_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, email, passwordHash, salt
func (_m *MockStorage) CreateUser(ctx context.Context, email string, passwordHash string, salt string) (*model.UserRecord, error) {
	ret := _m.Called(ctx, email, passwordHash, salt)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *model.UserRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.UserRecord, error)); ok {
		return rf(ctx, email, passwordHash, salt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.UserRecord); ok {
		r0 = rf(ctx, email, passwordHash, salt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, email, passwordHash, salt)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockStorage_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - passwordHash string
//   - salt string
func (_e *MockStorage_Expecter) CreateUser(ctx interface{}, email interface{}, passwordHash interface{}, salt interface{}) *MockStorage_CreateUser_Call {
	return &MockStorage_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, email, passwordHash, salt)}
}

func (_c *MockStorage_CreateUser_Call) Run(run func(ctx context.Context, email string, passwordHash string, salt string)) *MockStorage_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockStorage_CreateUser_Call) Return(_a0 *model.UserRecord, _a1 error) *MockStorage_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_CreateUser_Call) RunAndReturn(run func(context.Context, string, string, string) (*model.UserRecord, error)) *MockStorage_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, userID, secretID
func (_m *MockStorage) DeleteSecret(ctx context.Context, userID string, secretID string) error {
	ret := _m.Called(ctx, userID, secretID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, secretID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockStorage_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - secretID string
func (_e *MockStorage_Expecter) DeleteSecret(ctx interface{}, userID interface{}, secretID interface{}) *MockStorage_DeleteSecret_Call {
	return &MockStorage_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, userID, secretID)}
}

func (_c *MockStorage_DeleteSecret_Call) Run(run func(ctx context.Context, userID string, secretID string)) *MockStorage_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_DeleteSecret_Call) Return(_a0 error) *MockStorage_DeleteSecret_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_DeleteSecret_Call) RunAndReturn(run func(context.Context, string, string) error) *MockStorage_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretByID provides a mock function with given fields: ctx, userID, secretID
func (_m *MockStorage) GetSecretByID(ctx context.Context, userID string, secretID string) (*model.Secret, error) {
	ret := _m.Called(ctx, userID, secretID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretByID")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.Secret, error)); ok {
		return rf(ctx, userID, secretID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.Secret); ok {
		r0 = rf(ctx, userID, secretID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, secretID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetSecretByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretByID'
type MockStorage_GetSecretByID_Call struct {
	*mock.Call
}

// GetSecretByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - secretID string
func (_e *MockStorage_Expecter) GetSecretByID(ctx interface{}, userID interface{}, secretID interface{}) *MockStorage_GetSecretByID_Call {
	return &MockStorage_GetSecretByID_Call{Call: _e.mock.On("GetSecretByID", ctx, userID, secretID)}
}

func (_c *MockStorage_GetSecretByID_Call) Run(run func(ctx context.Context, userID string, secretID string)) *MockStorage_GetSecretByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockStorage_GetSecretByID_Call) Return(_a0 *model.Secret, _a1 error) *MockStorage_GetSecretByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetSecretByID_Call) RunAndReturn(run func(context.Context, string, string) (*model.Secret, error)) *MockStorage_GetSecretByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretsByUserID provides a mock function with given fields: ctx, userID
func (_m *MockStorage) GetSecretsByUserID(ctx context.Context, userID string) ([]model.Secret, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretsByUserID")
	}

	var r0 []model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]model.Secret, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []model.Secret); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetSecretsByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretsByUserID'
type MockStorage_GetSecretsByUserID_Call struct {
	*mock.Call
}

// GetSecretsByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockStorage_Expecter) GetSecretsByUserID(ctx interface{}, userID interface{}) *MockStorage_GetSecretsByUserID_Call {
	return &MockStorage_GetSecretsByUserID_Call{Call: _e.mock.On("GetSecretsByUserID", ctx, userID)}
}

func (_c *MockStorage_GetSecretsByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockStorage_GetSecretsByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetSecretsByUserID_Call) Return(_a0 []model.Secret, _a1 error) *MockStorage_GetSecretsByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetSecretsByUserID_Call) RunAndReturn(run func(context.Context, string) ([]model.Secret, error)) *MockStorage_GetSecretsByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *MockStorage) GetUserByEmail(ctx context.Context, email string) (*model.UserRecord, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 *model.UserRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*model.UserRecord, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *model.UserRecord); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_GetUserByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByEmail'
type MockStorage_GetUserByEmail_Call struct {
	*mock.Call
}

// GetUserByEmail is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockStorage_Expecter) GetUserByEmail(ctx interface{}, email interface{}) *MockStorage_GetUserByEmail_Call {
	return &MockStorage_GetUserByEmail_Call{Call: _e.mock.On("GetUserByEmail", ctx, email)}
}

func (_c *MockStorage_GetUserByEmail_Call) Run(run func(ctx context.Context, email string)) *MockStorage_GetUserByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStorage_GetUserByEmail_Call) Return(_a0 *model.UserRecord, _a1 error) *MockStorage_GetUserByEmail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_GetUserByEmail_Call) RunAndReturn(run func(context.Context, string) (*model.UserRecord, error)) *MockStorage_GetUserByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function with given fields: ctx
func (_m *MockStorage) Ping(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStorage_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorage_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorage_Expecter) Ping(ctx interface{}) *MockStorage_Ping_Call {
	return &MockStorage_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStorage_Ping_Call) Run(run func(ctx context.Context)) *MockStorage_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockStorage_Ping_Call) Return(_a0 error) *MockStorage_Ping_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStorage_Ping_Call) RunAndReturn(run func(context.Context) error) *MockStorage_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: ctx, userID, secretID, title, encryptedData, metadata, filePath
func (_m *MockStorage) UpdateSecret(ctx context.Context, userID string, secretID string, title string, encryptedData string, metadata string, filePath string) (*model.Secret, error) {
	ret := _m.Called(ctx, userID, secretID, title, encryptedData, metadata, filePath)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *model.Secret
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) (*model.Secret, error)); ok {
		return rf(ctx, userID, secretID, title, encryptedData, metadata, filePath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, string) *model.Secret); ok {
		r0 = rf(ctx, userID, secretID, title, encryptedData, metadata, filePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Secret)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, string) error); ok {
		r1 = rf(ctx, userID, secretID, title, encryptedData, metadata, filePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStorage_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockStorage_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - secretID string
//   - title string
//   - encryptedData string
//   - metadata string
//   - filePath string
func (_e *MockStorage_Expecter) UpdateSecret(ctx interface{}, userID interface{}, secretID interface{}, title interface{}, encryptedData interface{}, metadata interface{}, filePath interface{}) *MockStorage_UpdateSecret_Call {
	return &MockStorage_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, userID, secretID, title, encryptedData, metadata, filePath)}
}

func (_c *MockStorage_UpdateSecret_Call) Run(run func(ctx context.Context, userID string, secretID string, title string, encryptedData string, metadata string, filePath string)) *MockStorage_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(string))
	})
	return _c
}

func (_c *MockStorage_UpdateSecret_Call) Return(_a0 *model.Secret, _a1 error) *MockStorage_UpdateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStorage_UpdateSecret_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, string) (*model.Secret, error)) *MockStorage_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
