// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockproto

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	proto "gkeeper/api/proto"
)

// MockGKeeperClient is an autogenerated mock type for the GKeeperClient type
type MockGKeeperClient struct {
	mock.Mock
}

type MockGKeeperClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGKeeperClient) EXPECT() *MockGKeeperClient_Expecter {
	return &MockGKeeperClient_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockGKeeperClient) CreateSecret(ctx context.Context, in *proto.CreateSecretRequest, opts ...grpc.CallOption) (*proto.CreateSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *proto.CreateSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) (*proto.CreateSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) *proto.CreateSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.CreateSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGKeeperClient_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type MockGKeeperClient_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.CreateSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockGKeeperClient_Expecter) CreateSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockGKeeperClient_CreateSecret_Call {
	return &MockGKeeperClient_CreateSecret_Call{Call: _e.mock.On("CreateSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGKeeperClient_CreateSecret_Call) Run(run func(ctx context.Context, in *proto.CreateSecretRequest, opts ...grpc.CallOption)) *MockGKeeperClient_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.CreateSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGKeeperClient_CreateSecret_Call) Return(_a0 *proto.CreateSecretResponse, _a1 error) *MockGKeeperClient_CreateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGKeeperClient_CreateSecret_Call) RunAndReturn(run func(context.Context, *proto.CreateSecretRequest, ...grpc.CallOption) (*proto.CreateSecretResponse, error)) *MockGKeeperClient_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockGKeeperClient) DeleteSecret(ctx context.Context, in *proto.DeleteSecretRequest, opts ...grpc.CallOption) (*proto.DeleteSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 *proto.DeleteSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) (*proto.DeleteSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) *proto.DeleteSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.DeleteSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGKeeperClient_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type MockGKeeperClient_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.DeleteSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockGKeeperClient_Expecter) DeleteSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockGKeeperClient_DeleteSecret_Call {
	return &MockGKeeperClient_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGKeeperClient_DeleteSecret_Call) Run(run func(ctx context.Context, in *proto.DeleteSecretRequest, opts ...grpc.CallOption)) *MockGKeeperClient_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.DeleteSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGKeeperClient_DeleteSecret_Call) Return(_a0 *proto.DeleteSecretResponse, _a1 error) *MockGKeeperClient_DeleteSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGKeeperClient_DeleteSecret_Call) RunAndReturn(run func(context.Context, *proto.DeleteSecretRequest, ...grpc.CallOption) (*proto.DeleteSecretResponse, error)) *MockGKeeperClient_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockGKeeperClient) GetSecret(ctx context.Context, in *proto.GetSecretRequest, opts ...grpc.CallOption) (*proto.GetSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSecret")
	}

	var r0 *proto.GetSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) (*proto.GetSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) *proto.GetSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGKeeperClient_GetSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecret'
type MockGKeeperClient_GetSecret_Call struct {
	*mock.Call
}

// GetSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockGKeeperClient_Expecter) GetSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockGKeeperClient_GetSecret_Call {
	return &MockGKeeperClient_GetSecret_Call{Call: _e.mock.On("GetSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGKeeperClient_GetSecret_Call) Run(run func(ctx context.Context, in *proto.GetSecretRequest, opts ...grpc.CallOption)) *MockGKeeperClient_GetSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGKeeperClient_GetSecret_Call) Return(_a0 *proto.GetSecretResponse, _a1 error) *MockGKeeperClient_GetSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGKeeperClient_GetSecret_Call) RunAndReturn(run func(context.Context, *proto.GetSecretRequest, ...grpc.CallOption) (*proto.GetSecretResponse, error)) *MockGKeeperClient_GetSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecrets provides a mock function with given fields: ctx, in, opts
func (_m *MockGKeeperClient) GetSecrets(ctx context.Context, in *proto.GetSecretsRequest, opts ...grpc.CallOption) (*proto.GetSecretsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetSecrets")
	}

	var r0 *proto.GetSecretsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSecretsRequest, ...grpc.CallOption) (*proto.GetSecretsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.GetSecretsRequest, ...grpc.CallOption) *proto.GetSecretsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.GetSecretsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.GetSecretsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGKeeperClient_GetSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecrets'
type MockGKeeperClient_GetSecrets_Call struct {
	*mock.Call
}

// GetSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.GetSecretsRequest
//   - opts ...grpc.CallOption
func (_e *MockGKeeperClient_Expecter) GetSecrets(ctx interface{}, in interface{}, opts ...interface{}) *MockGKeeperClient_GetSecrets_Call {
	return &MockGKeeperClient_GetSecrets_Call{Call: _e.mock.On("GetSecrets",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGKeeperClient_GetSecrets_Call) Run(run func(ctx context.Context, in *proto.GetSecretsRequest, opts ...grpc.CallOption)) *MockGKeeperClient_GetSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.GetSecretsRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGKeeperClient_GetSecrets_Call) Return(_a0 *proto.GetSecretsResponse, _a1 error) *MockGKeeperClient_GetSecrets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGKeeperClient_GetSecrets_Call) RunAndReturn(run func(context.Context, *proto.GetSecretsRequest, ...grpc.CallOption) (*proto.GetSecretsResponse, error)) *MockGKeeperClient_GetSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, in, opts
func (_m *MockGKeeperClient) Login(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption) (*proto.LoginResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *proto.LoginResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) *proto.LoginResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.LoginResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.LoginRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGKeeperClient_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockGKeeperClient_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.LoginRequest
//   - opts ...grpc.CallOption
func (_e *MockGKeeperClient_Expecter) Login(ctx interface{}, in interface{}, opts ...interface{}) *MockGKeeperClient_Login_Call {
	return &MockGKeeperClient_Login_Call{Call: _e.mock.On("Login",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGKeeperClient_Login_Call) Run(run func(ctx context.Context, in *proto.LoginRequest, opts ...grpc.CallOption)) *MockGKeeperClient_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.LoginRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGKeeperClient_Login_Call) Return(_a0 *proto.LoginResponse, _a1 error) *MockGKeeperClient_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGKeeperClient_Login_Call) RunAndReturn(run func(context.Context, *proto.LoginRequest, ...grpc.CallOption) (*proto.LoginResponse, error)) *MockGKeeperClient_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, in, opts
func (_m *MockGKeeperClient) Register(ctx context.Context, in *proto.RegisterRequest, opts ...grpc.CallOption) (*proto.RegisterResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *proto.RegisterResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) (*proto.RegisterResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) *proto.RegisterResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.RegisterResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGKeeperClient_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockGKeeperClient_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.RegisterRequest
//   - opts ...grpc.CallOption
func (_e *MockGKeeperClient_Expecter) Register(ctx interface{}, in interface{}, opts ...interface{}) *MockGKeeperClient_Register_Call {
	return &MockGKeeperClient_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGKeeperClient_Register_Call) Run(run func(ctx context.Context, in *proto.RegisterRequest, opts ...grpc.CallOption)) *MockGKeeperClient_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.RegisterRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGKeeperClient_Register_Call) Return(_a0 *proto.RegisterResponse, _a1 error) *MockGKeeperClient_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGKeeperClient_Register_Call) RunAndReturn(run func(context.Context, *proto.RegisterRequest, ...grpc.CallOption) (*proto.RegisterResponse, error)) *MockGKeeperClient_Register_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function with given fields: ctx, in, opts
func (_m *MockGKeeperClient) UpdateSecret(ctx context.Context, in *proto.UpdateSecretRequest, opts ...grpc.CallOption) (*proto.UpdateSecretResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *proto.UpdateSecretResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateSecretRequest, ...grpc.CallOption) (*proto.UpdateSecretResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *proto.UpdateSecretRequest, ...grpc.CallOption) *proto.UpdateSecretResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.UpdateSecretResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *proto.UpdateSecretRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGKeeperClient_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type MockGKeeperClient_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - in *proto.UpdateSecretRequest
//   - opts ...grpc.CallOption
func (_e *MockGKeeperClient_Expecter) UpdateSecret(ctx interface{}, in interface{}, opts ...interface{}) *MockGKeeperClient_UpdateSecret_Call {
	return &MockGKeeperClient_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockGKeeperClient_UpdateSecret_Call) Run(run func(ctx context.Context, in *proto.UpdateSecretRequest, opts ...grpc.CallOption)) *MockGKeeperClient_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*proto.UpdateSecretRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockGKeeperClient_UpdateSecret_Call) Return(_a0 *proto.UpdateSecretResponse, _a1 error) *MockGKeeperClient_UpdateSecret_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGKeeperClient_UpdateSecret_Call) RunAndReturn(run func(context.Context, *proto.UpdateSecretRequest, ...grpc.CallOption) (*proto.UpdateSecretResponse, error)) *MockGKeeperClient_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGKeeperClient creates a new instance of MockGKeeperClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGKeeperClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGKeeperClient {
	mock := &MockGKeeperClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
