// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockfilestorage

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockFileStorage is an autogenerated mock type for the FileStorage type
type MockFileStorage struct {
	mock.Mock
}

type MockFileStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileStorage) EXPECT() *MockFileStorage_Expecter {
	return &MockFileStorage_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function with given fields: ctx, objectKey
func (_m *MockFileStorage) Delete(ctx context.Context, objectKey string) error {
	ret := _m.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, objectKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileStorage_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFileStorage_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockFileStorage_Expecter) Delete(ctx interface{}, objectKey interface{}) *MockFileStorage_Delete_Call {
	return &MockFileStorage_Delete_Call{Call: _e.mock.On("Delete", ctx, objectKey)}
}

func (_c *MockFileStorage_Delete_Call) Run(run func(ctx context.Context, objectKey string)) *MockFileStorage_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFileStorage_Delete_Call) Return(_a0 error) *MockFileStorage_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileStorage_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockFileStorage_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Download provides a mock function with given fields: ctx, objectKey
func (_m *MockFileStorage) Download(ctx context.Context, objectKey string) ([]byte, error) {
	ret := _m.Called(ctx, objectKey)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, objectKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, objectKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, objectKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFileStorage_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockFileStorage_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
func (_e *MockFileStorage_Expecter) Download(ctx interface{}, objectKey interface{}) *MockFileStorage_Download_Call {
	return &MockFileStorage_Download_Call{Call: _e.mock.On("Download", ctx, objectKey)}
}

func (_c *MockFileStorage_Download_Call) Run(run func(ctx context.Context, objectKey string)) *MockFileStorage_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockFileStorage_Download_Call) Return(_a0 []byte, _a1 error) *MockFileStorage_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFileStorage_Download_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockFileStorage_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function with given fields: ctx, objectKey, data
func (_m *MockFileStorage) Upload(ctx context.Context, objectKey string, data []byte) error {
	ret := _m.Called(ctx, objectKey, data)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, objectKey, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFileStorage_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type MockFileStorage_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - objectKey string
//   - data []byte
func (_e *MockFileStorage_Expecter) Upload(ctx interface{}, objectKey interface{}, data interface{}) *MockFileStorage_Upload_Call {
	return &MockFileStorage_Upload_Call{Call: _e.mock.On("Upload", ctx, objectKey, data)}
}

func (_c *MockFileStorage_Upload_Call) Run(run func(ctx context.Context, objectKey string, data []byte)) *MockFileStorage_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockFileStorage_Upload_Call) Return(_a0 error) *MockFileStorage_Upload_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFileStorage_Upload_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockFileStorage_Upload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFileStorage creates a new instance of MockFileStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileStorage {
	mock := &MockFileStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
